### ISSUE TITLE
how to improve video quality using flashywrapper

### ISSUE THREAD

**Issue by chaurasiadilip** [rainbowcreatures/FlashyWrappers#20]
hi,
i  am creating  air application to record video using flashyWrapper API . i am recording video with  1080x1920 resolution. but i got  pix elated video. so i want to improve video quality . so what will i have to do for improving video quality. so please guide me

  Thanks in advance

**Comment by zenrobin** [comment]
some tips I have found to be useful:

* limit your fps -- the lower number of frames, the better the quality (to an extent). If you're trying to encode 60fps at 1080x1920, you're going to need a very high bitrate than at 30fps or 20fps. 
* increase your bitrate -- follow YouTube's bitrate guidelines via google search, or just increase it to like 10MBps to ensure the bitrate isn't the problem, then gradually reduce
* don't use preset encoder settings for more control: instead of using "medium" or "high" quality, set it to passthrough which will try to use your custom bitrate settings rather than the preset. 
* try smaller resolution first. Again, use YouTube's bitrates as a guide for aggressive quality / size bitrate settings.  1280x720 at 3Mbps and 20 fps should produce a good quality file that is reasonably small (and therefore shareable, if that's a priority to you).

**Comment by chaurasiadilip** [comment]
Thanks zenrobin for replying.
Actually i am recording with chroma key . i am using sparkoCam software  to do chromakey.

**Comment by rainbowcreatures** [comment]
Thanks for those tips zenrobin!
