### ISSUE TITLE
animate cc and air package

### ISSUE THREAD

**Issue by alpoman** [rainbowcreatures/FlashyWrappers#25]
Hello, when i try to add the desktop ane to my air project in animate cc, the "output as air package" get grayed out and wont let me create an air file.  anyone know about this, thanks in advance!!

andy

**Comment by rainbowcreatures** [comment]
Hey Andy, you'll need to use native package installer - air packages don't work with ANE's.  See for example:

http://stackoverflow.com/questions/15053814/signed-air-package-vs-signed-native-installer

**Comment by alpoman** [comment]
so are you saying that i cant make an air file file an ane?  i know i can make a windows exe, but i need an air file that will work on mac as well,  thanks!

**Comment by rainbowcreatures** [comment]
Well, on Mac you need to export as .dmg (native installer) which installs it as native app on the users Mac. As far as I know thats the only way you can deploy AIR apps together with ANE's on Mac.

**Comment by alpoman** [comment]
so can air use .swc but not ane?  is there a swc of flashywrappers that will work for air package? thanks!

**Comment by rainbowcreatures** [comment]
Yeah, if you don't package it as native installer you can use swc's, but not native code. 

The problem with swc is, its not native code...its interpreted by the virtual machine. In theory the Flash version of FlashyWrappers (which is swc) might work on Mac with some adjustments, but it would be several times slower than the ANE, which works with native Apple libraries (and you would lose the ability to produce mp4, for that I'm calling Apple API's again, so that also makes it legal, vs. embedding your own encoder into swc and redistributing it with the app).

**Comment by alpoman** [comment]
thank you for this detailed explanation--  it makes sense to me.  so if i want a version of my app to work on mac, i need to run the mac version of animate cc so i can get the create .dmg option,  like the create .exe version i have for windows.   thank you again!  
andy

**Comment by rainbowcreatures** [comment]
Yep, exactly!
