### ISSUE TITLE
changing bitrate in encoder.start() does not change the bitrate in the video file

### ISSUE THREAD

**Issue by Igazine** [rainbowcreatures/FlashyWrappers#28]
Hello,

here's a simple line of code i'm using to test FW.

`encoder.start( fps, FWVideoEncoder.AUDIO_OFF, false, 0, 0, bitrate );`

bitrate variable is set to 10000000, however it doesn't matter what I do with it, the exported video bitrate is always ~110kbps (at 25 fps)

Please assist
Thank you

**Comment by Igazine** [comment]
Notes:

- it's tested on Windows
- i've added some more complex bitmaps in the background and although the bitrate has changed, it's still not the desired quality (1000kbps currently)

**Comment by rainbowcreatures** [comment]
I'll test this out when I get a chance, most likely weekend - 

Which version of Windows ?

**Comment by Igazine** [comment]
Windows 10, latest AIR 25 production
Everything works smoothly, I've experienced no bugs, the only issue I've found so far is the quality of the rendered video
Thank you

**Comment by rainbowcreatures** [comment]
Ok, got it

**Comment by rainbowcreatures** [comment]
Hey so, I finally got around to test it successfully, couldn't make the new Animate CC working with my ANE, turns out it was erasing the extension ID from XML for some reason.

I tested this with AIR 24 (but that shouldn't make any difference), and the bitrate seemed to work - I used "Bitrate Viewer", where I tested 1000kbps, 5000kbps (and it was showing those numbers in Bitrate Viewer), then 100kbps and the quality sucked. The different bitrates also were showing in different filesizes.

So I'm not sure what quality you experience if you try to bump up the bitrate like 5x more, maybe you could link to a video. It might be different factors influencing the video quality. Perhaps try to check with the Bitrate Viewer or similar tool as well, to rule out the bitrate issue. Maybe for you it really doesn't change, not sure.

Tested on:

Windows 10 Home
Version 1607
Build 14393.1066

**Comment by Igazine** [comment]
Thanks for testing it.
You may close this issue.
