### ISSUE TITLE
Question related to FW "Standard"

### ISSUE THREAD

**Issue by idzdigital** [rainbowcreatures/FlashyWrappers#56]
Hi I tried Free version of Flashy Wrappers for recording video in my AIR application. Its working for me.
I have few question before I purchase it for commercial use.
1. Since the last update was 5 years ago does it support video recording in all new mobile devices?
2. WIll the FW "Standard" record video in mp4 just like free version? since it is mentioned on the site that there is no Android MP4 encoder in FW "Standard".
3. Is the code optimized to support 64-Bit requirement of Google Play Store? [https://developer.android.com/distribute/best-practices/develop/64-bit](https://developer.android.com/distribute/best-practices/develop/64-bit)

**Comment by rainbowcreatures** [comment]
Hey, 

FW SDK as I'm aware still does work surprisingly well even today, but I stopped actively developing it  years ago as the sales almost stopped in the past years, together with AIR usage decline. I still do support the rare client who purchases this from time to time. If smaller issues pop up, I am trying to help, but I won't put lots of hours into it anymore (such as supporting new devices etc.).

1. I can't say, the only way is to test this is trying it yourself on devices of interest with the free version. The code does use pretty old and low level techniques for the video recording which I suppose hardly change in the Android API's, so it has been pretty stable throughout the years. I'd assume capturing in non-realtime mode (avoiding the fast WebGL capture) should be pretty reliable. If you plan to use WebGL / fast realtime capture on Android, results might vary.
2. Yes, FW "Standard" doesn't have Android included as historically there was always higher likelyhood of support requests for Android than for iOS due to the range of Android devices.
3. Yes, FW includes 64 bit extension support, 64 bit accross platforms is one of the few things I was willing to work on despite the lack of other updates. Here's the manifest file for the Android extension:

```
<extension xmlns="http://ns.adobe.com/air/extension/20.0">
    <id>com.rainbowcreatures.FWEncoderANE</id>
    <versionNumber>1</versionNumber>
    <platforms>
	<platform name="Android-ARM">
		<applicationDeployment>
			<nativeLibrary>FlashyWrappers.jar</nativeLibrary>
			<initializer>com.rainbowcreatures.FlashyWrappersAndroidHW.FlashyWrappers</initializer>
			<finalizer>com.rainbowcreatures.FlashyWrappersAndroidHW.FlashyWrappers</finalizer>
		</applicationDeployment>
	</platform>
	<platform name="Android-ARM64">
		<applicationDeployment>
			<nativeLibrary>FlashyWrappers.jar</nativeLibrary>
			<initializer>com.rainbowcreatures.FlashyWrappersAndroidHW.FlashyWrappers</initializer>
			<finalizer>com.rainbowcreatures.FlashyWrappersAndroidHW.FlashyWrappers</finalizer>
		</applicationDeployment>
	</platform>
	<platform name="Android-x86">
		<applicationDeployment>
			<nativeLibrary>FlashyWrappers.jar</nativeLibrary>
			<initializer>com.rainbowcreatures.FlashyWrappersAndroidHW.FlashyWrappers</initializer>
			<finalizer>com.rainbowcreatures.FlashyWrappersAndroidHW.FlashyWrappers</finalizer>
		</applicationDeployment>
	</platform>
    </platforms>
</extension>

```

Overall, I'd suggest testing with the free version as much as possible before you commit to a purchase as there has been no testing going on my side for several years.

Thanks!
Pavel

**Comment by idzdigital** [comment]
Hi,
Thanks for the reply.
Second point is still not very clear. I have added free version of Flashy Wrapper in Android AIR app to record mp4 video. It gives me mp4 output as expected. Will I get same mp4 output if I purchase FW "Standard"?

**Comment by rainbowcreatures** [comment]
Hello there, 

You're welcome (and sorry for the delay of 2 days). Android is not included in Standard. It's included in the Free version, so everyone can try it out, and then in the Premium version. If you wish to further discuss we can continue at info at flashywrappers.com rather than here.

![image](https://user-images.githubusercontent.com/10990888/145247569-6ee43f95-cf18-450c-906e-d0e22d1a42e7.png)

Thanks!

**Comment by idzdigital** [comment]
ok thanks.closing this now.

**Comment by idzdigital** [comment]
Hi, 
We have purchased FW Premium but have not received any code files yet. Our email id is info@touchzing.com. Please send the code files.
Thanks!

**Comment by idzdigital** [comment]
Hi,
We have purchased FW Premium but have not received any code files yet. Our email id is info@touchzing.com. Please send the code files.
Thanks!

**Comment by rainbowcreatures** [comment]
Finally, you emailed me :) GitHub is not great for these sorts of requests. Thanks!
